version: '3.8'
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime
      - /var/run/docker.sock:/var/run/docker.sock
      - /DATA/AppData/portainer:/data
    network_mode: host
############################################
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /DATA/AppData/homarr/configs:/app/data/configs
      - /DATA/AppData/homarr/icons:/app/public/icons
      - /DATA/AppData/homarr/data:/data
    ports:
      - '7575:7575'
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    blkio_config:
      weight: 300
    network_mode: host
############################################
  jellyfin:
    container_name: jellyfin
    image: lscr.io/linuxserver/jellyfin:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
    - /DATA/AppData/jellyfin/library:/config
    - /DATA/Media:/data/media
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 6024M
    blkio_config:
      weight: 800
    network_mode: host
############################################
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
        - LOG_LEVEL=info
        - TTZ=America/Sao_Paulo
    ports:
        - 5055:5055
    volumes:
        - /DATA/AppData/jellyseerr/config:/app/config
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 1024M
    blkio_config:
      weight: 400
    network_mode: host
############################################
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - /DATA/AppData/prowlarr/data:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 524M
    blkio_config:
      weight: 100
    network_mode: host
############################################
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - WEBUI_PORT=8081
      - TORRENTING_PORT=6881
    volumes:
      - /DATA/AppData/qbittorrent:/config
      - /DATA/Media/Downloads:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    blkio_config:
      weight: 200
    network_mode: host
############################################
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - /DATA/AppData/radarr/data:/config
      - /DATA/Media/Movies:/movies
      - /DATA/Media/Downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '3'
          memory: 1024M
    blkio_config:
      weight: 400
    network_mode: host
############################################
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - /DATA/AppData/sonarr:/config
      - /DATA/Media/TV Shows:/tvshows
      - /DATA/Media/Downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1024M
    blkio_config:
      weight: 400
    network_mode: host